version: '3.8'
services:
  app:
    build: ./
    ports:
      - 3001:3000
    env_file:
      - .env
    networks:
      - jtools
  ghost:
    image: 5.74.0-alpine
    environment:
      - url=http://localhost:2368
    ports:
      - 2368:2368
  nginx:
    image: nginx:1.25.3-alpine
    
networks:
  jtools: