version: '3.8'
services:
  app:
    build: ./
    env_file:
      - .env
    networks:
      - jtools
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf # replace nginx.dev.conf with nginx.prod.conf when deploying to production
    networks:
      - jtools
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - jtools
  minio:
    image: bitnami/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - jtools
networks:
  jtools:
volumes:
  minio:
  mongo: