version: '3.8'
services:
  # app:
  #   build: ./
  #   ports:
  #     - 3001:3000
  #   env_file:
  #     - .env
  #   networks:
  #     - jtools
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - jtools
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - jtools
  minio:
    image: bitnami/minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - jtools
networks:
  jtools: